"""
Django settings for the MediDiagnose project.

Generated by 'django-admin startproject' using Django 5.2.
Configured with django-environ for environment variable management.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

import environ

# =============================================================================
# Path Configuration
# =============================================================================
BASE_DIR: Path = Path(__file__).resolve().parent.parent

# =============================================================================
# Environment Variables (django-environ)
# =============================================================================
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
)
environ.Env.read_env(BASE_DIR / ".env")

# =============================================================================
# Core Settings
# =============================================================================
SECRET_KEY: str = env("SECRET_KEY")
DEBUG: bool = env("DEBUG")
ALLOWED_HOSTS: list[str] = env("ALLOWED_HOSTS")

# =============================================================================
# Application Definition
# =============================================================================
INSTALLED_APPS: list[str] = [
    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "django_extensions",
    # Project apps
    "knowledge_base.apps.KnowledgeBaseConfig",
    "inference_engine.apps.InferenceEngineConfig",
    "patient_cases.apps.PatientCasesConfig",
    "explanations.apps.ExplanationsConfig",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF: str = "medidiagnose.urls"

TEMPLATES: list[dict] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION: str = "medidiagnose.wsgi.application"

# =============================================================================
# Database – PostgreSQL via DATABASE_URL
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# =============================================================================
DATABASES: dict = {
    "default": env.db("DATABASE_URL"),
}

# =============================================================================
# Password Validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# =============================================================================
AUTH_PASSWORD_VALIDATORS: list[dict] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =============================================================================
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# =============================================================================
LANGUAGE_CODE: str = "en-us"
TIME_ZONE: str = "UTC"
USE_I18N: bool = True
USE_TZ: bool = True

# =============================================================================
# Static Files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# =============================================================================
STATIC_URL: str = "static/"

# =============================================================================
# Default Primary Key Field Type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# =============================================================================
DEFAULT_AUTO_FIELD: str = "django.db.models.BigAutoField"
