# Generated by Django 5.2.11 on 2026-02-14 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique disease name.', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Clinical description of the disease.')),
                ('treatments', models.TextField(help_text='Recommended treatments and interventions.')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Clinical urgency level.', max_length=10)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['-urgency_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique symptom name.', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('RESPIRATORY', 'Respiratory'), ('DIGESTIVE', 'Digestive'), ('NEUROLOGICAL', 'Neurological')], default='GENERAL', help_text='Broad medical category this symptom belongs to.', max_length=20)),
                ('severity_weight', models.PositiveSmallIntegerField(default=1, help_text='Relative severity weight (higher = more severe).')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short descriptive rule name.', max_length=200)),
                ('confidence_factor', models.PositiveSmallIntegerField(help_text='Rule confidence factor (0–100 %).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('explanation_template', models.TextField(help_text='Human-readable explanation template. Use {symptoms} and {disease} as placeholders.')),
                ('then_disease', models.ForeignKey(help_text='Disease concluded when this rule fires.', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_rules', to='knowledge_base.diseasemodel')),
                ('if_symptoms', models.ManyToManyField(help_text='Symptoms that must be present for this rule to fire.', related_name='rules_containing', to='knowledge_base.symptommodel')),
            ],
            options={
                'verbose_name': 'Diagnostic Rule',
                'verbose_name_plural': 'Diagnostic Rules',
                'ordering': ['name'],
                'unique_together': {('name', 'then_disease')},
            },
        ),
    ]
