# Generated by Django 5.2.11 on 2026-02-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceTraceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when inference was executed.')),
                ('strategy_used', models.CharField(choices=[('FORWARD_CHAINING', 'Forward Chaining'), ('BACKWARD_CHAINING', 'Backward Chaining')], help_text='Inference strategy that was applied.', max_length=20)),
                ('rules_fired', models.JSONField(default=list, help_text='JSON list of rules that fired during inference, e.g. [{"rule_id": 1, "name": "Rule-Flu-01", "confidence": 85}].')),
                ('confidence_scores_calculated', models.JSONField(default=dict, help_text='JSON dict mapping disease IDs/names to calculated confidence scores, e.g. {"Flu": 85.0, "Cold": 60.5}.')),
                ('execution_time_ms', models.PositiveIntegerField(help_text='Inference execution time in milliseconds.')),
                ('patient_case', models.ForeignKey(help_text='The patient case this inference trace belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to='patient_cases.patientcasemodel')),
            ],
            options={
                'verbose_name': 'Inference Trace',
                'verbose_name_plural': 'Inference Traces',
                'ordering': ['-execution_timestamp'],
            },
        ),
    ]
