# Generated by Django 5.2.11 on 2026-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identifier', models.CharField(help_text='Opaque patient or session identifier.', max_length=100)),
                ('session_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this diagnostic session was created.')),
                ('reported_symptoms_snapshot', models.JSONField(default=list, help_text='JSON list of symptom dicts, e.g. [{"id": 1, "name": "Fever"}].')),
                ('inferred_results', models.JSONField(default=list, help_text='Ranked list of inferred diseases with confidence scores, e.g. [{"disease_id": 1, "disease_name": "Flu", "confidence": 85.0}].')),
                ('applied_rules_trace', models.JSONField(default=list, help_text='Trace of rules that fired during inference, e.g. [{"rule_id": 1, "explanation": "..."}].')),
                ('final_diagnosis_notes', models.TextField(blank=True, default='', help_text='Optional clinician notes after reviewing inference results.')),
            ],
            options={
                'verbose_name': 'Patient Case',
                'verbose_name_plural': 'Patient Cases',
                'ordering': ['-session_date'],
            },
        ),
    ]
